site_name: Hack Clio
site_author: Isaac Leinweber <brotchen@gmail.com>
repo_url: https://github.com/kilahm/HackClio

theme: readthedocs

pages:
    - ['index.md', 'Home']
    - ['about.md', 'About']
    - ['guide/intro.md', 'User Guide', 'Introduction']
    - ['guide/argsAndOptions.md', 'User Guide', 'Arguments and Options']
