site_name: Hack Clio
site_author: Isaac Leinweber <brotchen@gmail.com>
repo_url: https://github.com/kilahm/HackClio

theme: readthedocs
markdown_extensions: ['codehilite']
pages:
    - ['index.md', 'Home']
    - ['guide/intro.md', 'User Guide', 'Introduction']
    - ['guide/argsAndOptions.md', 'User Guide', 'Arguments and Options']
    - ['guide/formatsAndColors.md', 'User Guide', 'Formatting Output']
    - ['guide/questions.md', 'User Guide', 'Asking Questions']
